import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { Providers } from "./providers";

const androgyDemo = localFont({
  src: "../public/fonts/AndrogyDemo.ttf",
  variable: "--font-androgy-demo",
});

const typeMachine = localFont({
  src: "../public/fonts/TypeMachine.ttf",
  variable: "--font-type-machine",
});

export const metadata: Metadata = {
  title: "Towns And Seas",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* Add both font variables to the body */}
      <body className={`${androgyDemo.variable} ${typeMachine.variable} antialiased bg-[#F9EFE8]`}>
        <Providers>
          <Header/>
          {children}
          <Footer/>
        </Providers>
      </body>
    </html>
  );
}